spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/silog_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false

server:
  port: ${PORT:8080}
